image: visual studio 2019
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    
install:

build_script:
  - Build.cmd

clone_depth: 1
test: off
deploy: off

artifacts:
  - path: src\artifacts\**\*.nupkg
